### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by saurabhnemade** [apearce/react-shadow-root#3]
How to use it in typescript react application?

**Comment by pavelstudeny** [comment]
I have added this to my project:
`
declare module "index" {
    export var __esModule: boolean;
    var _default: any;
    export default _default;
}
`

**Comment by saurabhnemade** [comment]
It's a solution but again it's defeating the purpose of typescript. If I have to declare `any` for a module with certain api and props then I could have choses to go with JS boilerplate where things get messy.

**Comment by apearce** [comment]
Sorry, I have not used typescript. I thought it was supposed to just work. I'll have to look into it.

**Comment by Ozea** [comment]
To use this library in typescript a possible workaround can be:

- Create 'types' folder ( or whatever you want ) in 'src' of your project
- In 'types' folder create a folder with 3rd party library name ( better to use its exact name ) and inside it create a file named '3rd-party-library-name.d.ts'
- Inside that file type this `declare module '3rd-party-library-name'`
- In tsconfig.json file insert this
`"include": [
    "./types/**/*d.ts"
  ]`

After these easy steps just import required 3rd party library!
It's just a **workaround** and OF COURSE to create library types is a must

Hope it helps and saves smbd

**Comment by apearce** [comment]
Typescript definitions have been added thanks to @andersthorsen 
Version 6.1.0 has them.
